//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyManagerToUniversity.model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MoneyManagerEntities : DbContext
    {
        public MoneyManagerEntities()
            : base("name=MoneyManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<bank> bank { get; set; }
        public virtual DbSet<bank_account> bank_account { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<expenses> expenses { get; set; }
        public virtual DbSet<expenses_type> expenses_type { get; set; }
        public virtual DbSet<incomes> incomes { get; set; }
        public virtual DbSet<incomes_type> incomes_type { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
